#!/bin/sh

# Configure
BORDER_WIDTH=4
GAP_WIDTH=64

BORDER_COLOUR="#585858"
BORDER_COLOUR_FOCUSED="#86c1b9"

BACKGROUND_COLOUR="#000000"

# Execute
bspc config border_width		$BORDER_WIDTH
bspc config window_gap			$GAP_WIDTH

bspc config split_ratio         	0.50
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true

bspc config normal_border_color 	$BORDER_COLOUR
bspc config focused_border_color	$BORDER_COLOUR_FOCUSED

bspc monitor -d				1 2 3 4 5 6 7 8 9

hsetroot -solid			    	$BACKGROUND_COLOUR
