#! /bin/sh

yabar &
~/scripts/bspwmtray.sh &
feh ~/wallpapers/win3_1.png --bg-fill &
compton &
lxpolkit &
sxhkd &

bspc config border_width    2
bspc config window_gap      12
bspc config top_padding     18 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config normal_border_color     "#798086"
bspc config active_border_color     "#d8d8d8"
bspc config focused_border_color    "#92bbed"
bspc config presel_feedback_color   "#92bbed"
